# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
# Lock screen on lid close / sleep
exec-once = hypridle
exec-once = hyprpaper
exec-once = waybar
exec-once = waypaper --restore
exec-once = uwsma-app mako

exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR

