windowrule {
# Ignore maximize requests from all apps. You'll probably like this.
name = suppress-maximize-events
match:class = .*

suppress_event = maximize
}

windowrule {
# Fix some dragging issues with XWayland
name = fix-xwayland-drags
match:class = ^$
match:title = ^$
match:xwayland = true
match:float = true
match:fullscreen = false
match:pin = false

no_focus = true
}

# Hyprland-run windowrule
windowrule {
name = move-hyprland-run

match:class = hyprland-run

move = 20 monitor_h-120
float = yes
}

# Make impala window float and appear on top
windowrule {
name = impala-float
match:class = ^(Alacritty)$
match:title = ^(impala)$

float = true
center = true
size = 800 600
}
# Make btop window float and appear on top
windowrule {
name = btop-float
match:class = ^(Alacritty)$
match:title = ^(btop)$

float = true
center = true
size = 800 530
}
# Make bluetui window float and appear on top
windowrule {
name = bluetui-float
match:class = ^(Alacritty)$
match:title = ^(bluetui)$

float = true
center = true
size = 725 530
}
# Make wiremix window float and appear on top
windowrule {
name = wiremix-float
match:class = ^(Alacritty)$
match:title = ^(wiremix)$
float = true
center = true
size = 700 430
}
# Window rules for web apps

windowrule {
name = brave-webapp
match:class = ^(brave-.*)$
float = false
center = false
size = 1400 900

}
windowrule {
name = yayfzf-float
match:class = ^(Alacritty)$
match:title = ^(yayfzf)$
float = true
center = true
size = 700 430
}
windowrule {
    name = steam-filepicker
    match:class = ^(steam)$
    match:title = ^(Open)$
    float = true
    center = true
    size = 900 600
}